import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";
import { GlobalStateProvider } from "@/context/GlobalStateContext";
import { Bounce, ToastContainer } from "react-toastify";

const montserrat = Montserrat({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  fallback: ["Arial", "sans-serif"],
});

const xeroda = localfont({
  src: [
    {
      path: "../../public/xeroda-font/XerodaRegular-p7dwr.otf",
    },
  ],
  variable: "--font-xeroda",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${xeroda.variable} ${montserrat.className} h-full relative bg-[#0f1114] text-white`}
      >
        <GlobalStateProvider>
          {children}
          <ToastContainer
            theme="dark"
            position="top-right"
            autoClose={5000}
            pauseOnFocusLoss
            draggable
            pauseOnHover
          />
        </GlobalStateProvider>
      </body>
    </html>
  );
}
